apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: jmccoydev/tasky:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:adminPassword@10.0.4.229:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: tasky
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: tasky
