apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: wiz-cluster-admin
      containers:
      - name: tasky
        image: jmccoydev/tasky:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:adminPassword@10.0.4.227:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: tasky
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: tasky
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiz-cluster-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: wiz-cluster-admin
  namespace: default
